version: '3'

volumes:
  s3_storage:
    external: true

services:
    minio:
        image: minio/minio:latest
        command: server /data --console-address ":9090"
        ports:
         - "9000:9000"
         - "9001:9001"
        environment:
          MINIO_ROOT_USER: admin
          MINIO_ROOT_PASSWORD: minio_admin
        volumes:
           - s3_storage:/datas
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
